FROM composer:1.9 as vendor
COPY database/ database/
COPY composer.json composer.json
COPY composer.lock composer.lock
RUN composer install --no-scripts --ansi --no-interaction

FROM node:12.12 as frontend
RUN mkdir -p /app/public
COPY package..json webpack.mix.js /app/
COPY resources/ /app/resources/
WORKDIR /app
RUN npm install && npm run dev

FROM php:7.3.10-apache-strech
RUN docker-php-ext-install pdo_mysql


COPY --chown=ww-data:ww-dat
a . /var/www/html
